<?php

namespace ContainerLd3HIcM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpellRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SpellRepository' shared autowired service.
     *
     * @return \App\Repository\SpellRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SpellRepository'] = new \App\Repository\SpellRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
