<?php

namespace ContainerLd3HIcM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\TagFormType' shared autowired service.
     *
     * @return \App\Form\TagFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TagFormType'] = new \App\Form\TagFormType();
    }
}
