<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLd3HIcM\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLd3HIcM/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLd3HIcM.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLd3HIcM\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerLd3HIcM\App_KernelProdContainer([
    'container.build_hash' => 'Ld3HIcM',
    'container.build_id' => 'f8344c29',
    'container.build_time' => 1625319369,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLd3HIcM');
