<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'createSpell' => [[], ['_controller' => 'App\\Controller\\FormController::createSpell'], [], [['text', '/spells/create']], [], []],
    'createTag' => [[], ['_controller' => 'App\\Controller\\FormController::createTag'], [], [['text', '/tags/create']], [], []],
];
