<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPkBCggh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPkBCggh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPkBCggh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPkBCggh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPkBCggh\App_KernelDevDebugContainer([
    'container.build_hash' => 'PkBCggh',
    'container.build_id' => '178523fc',
    'container.build_time' => 1625319458,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPkBCggh');
