<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Spell extends \App\Entity\Spell implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'tradition', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'rank', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'label', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'area', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'duration', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'target', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'requirement', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'damage', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'twentyPlus', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'triggered', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'sacrifice', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'tags'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'tradition', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'rank', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'label', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'area', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'duration', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'target', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'requirement', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'damage', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'twentyPlus', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'triggered', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'sacrifice', '' . "\0" . 'App\\Entity\\Spell' . "\0" . 'tags'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Spell $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTradition(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTradition', []);

        return parent::getTradition();
    }

    /**
     * {@inheritDoc}
     */
    public function setTradition(string $tradition): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTradition', [$tradition]);

        return parent::setTradition($tradition);
    }

    /**
     * {@inheritDoc}
     */
    public function getRank(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRank', []);

        return parent::getRank();
    }

    /**
     * {@inheritDoc}
     */
    public function setRank(int $rank): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRank', [$rank]);

        return parent::setRank($rank);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel(string $label): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', []);

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea(?string $area): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', [$area]);

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', []);

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration(?string $duration): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', [$duration]);

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarget(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarget', []);

        return parent::getTarget();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarget(?string $target): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarget', [$target]);

        return parent::setTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequirement(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequirement', []);

        return parent::getRequirement();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequirement(?string $requirement): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequirement', [$requirement]);

        return parent::setRequirement($requirement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDamage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDamage', []);

        return parent::getDamage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDamage(?string $damage): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDamage', [$damage]);

        return parent::setDamage($damage);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwentyPlus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwentyPlus', []);

        return parent::getTwentyPlus();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwentyPlus(?string $twentyPlus): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwentyPlus', [$twentyPlus]);

        return parent::setTwentyPlus($twentyPlus);
    }

    /**
     * {@inheritDoc}
     */
    public function getTriggered(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTriggered', []);

        return parent::getTriggered();
    }

    /**
     * {@inheritDoc}
     */
    public function setTriggered(?string $triggered): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTriggered', [$triggered]);

        return parent::setTriggered($triggered);
    }

    /**
     * {@inheritDoc}
     */
    public function getSacrifice(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSacrifice', []);

        return parent::getSacrifice();
    }

    /**
     * {@inheritDoc}
     */
    public function setSacrifice(?string $sacrifice): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSacrifice', [$sacrifice]);

        return parent::setSacrifice($sacrifice);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', []);

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function addTag(\App\Entity\Tag $tag): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTag', [$tag]);

        return parent::addTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTag(\App\Entity\Tag $tag): \App\Entity\Spell
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTag', [$tag]);

        return parent::removeTag($tag);
    }

}
